### ISSUE TITLE
not work link

### ISSUE THREAD

**Issue by andruwa13** [chitter99/mattermost-hangout#1]
Hello, thank you for your work. Not work link
![test - webakcent-it mattermost 2017-07-04 11-02-41](https://user-images.githubusercontent.com/5846351/27820734-6961fee4-60a8-11e7-88fc-962ef00b8da1.png)

- logs docker container:
![rancher 2017-07-04 11-05-13](https://user-images.githubusercontent.com/5846351/27820862-ee4a0728-60a8-11e7-8d8a-1f1dd2805885.png)

-  check:
![mattermost hangout plugin 2017-07-04 11-13-20](https://user-images.githubusercontent.com/5846351/27821128-e10f1444-60a9-11e7-90ca-9b9f610dd605.png)

**Comment by chitter99** [comment]
Hi @andruwa13,
Check the Configuration of the linked Google Calendar. 
The setting `Automatically add video calls to events I create` needs to be set to `true`.

**Comment by anwiev** [comment]
@chitter99, 
Hi, I have the same issue and in the setting 'Automatically add video calls to events I create' switched on. Could you help me, please?
![image](https://user-images.githubusercontent.com/50668058/105008797-63954380-5a42-11eb-8173-56d2701c946c.png)
![image](https://user-images.githubusercontent.com/50668058/105008982-9b03f000-5a42-11eb-8580-d8aac1065e8f.png)
![image](https://user-images.githubusercontent.com/50668058/105009357-0948b280-5a43-11eb-853a-8665d2f1feae.png)
![image](https://user-images.githubusercontent.com/50668058/105009535-4319b900-5a43-11eb-8604-8ee4762a3267.png)
![image](https://user-images.githubusercontent.com/50668058/105009632-617fb480-5a43-11eb-9ce8-c64ebaf7a8ed.png)
