### ISSUE TITLE
not work mattermost 4.2

### ISSUE THREAD

**Issue by andruwa13** [chitter99/mattermost-hangout#2]
Hello, not work send messages
![_test_-_it_mattermost_2017-09-18_10-37-10](https://user-images.githubusercontent.com/5846351/30532556-9a042aa4-9c5d-11e7-8b90-6150c42f19ec.png)

P.S. 4.1 work 
![_dev_group_-_it_mattermost_2017-09-18_10-39-42](https://user-images.githubusercontent.com/5846351/30532589-bc7f7e1c-9c5d-11e7-81ee-853ae4fb7279.png)

**Comment by MateuszKubuszok** [comment]
Indeed something seems to be broken in newest version

**Comment by andruwa13** [comment]
![mattermost changelog mattermost 4 3 documentation 2017-09-27 20-03-32](https://user-images.githubusercontent.com/5846351/30926884-4a91884a-a3bf-11e7-82ac-8b9d2e6e58b5.png)

**Comment by chitter99** [comment]
Hi there,
Sorry for keeping you waiting for so long.
I fixed our issue. The problem was just like you announced.
Tell me if the new version works on your side.
Best regards

**Comment by andruwa13** [comment]
not work(
![test - it mattermost 2017-11-08 15-47-46](https://user-images.githubusercontent.com/5846351/32552313-31272cae-c49c-11e7-9130-198f60c0baf7.png)
