### ISSUE TITLE
Share your work with Mattermost community?

### ISSUE THREAD

**Issue by jasonblais** [chitter99/mattermost-hangout#3]
Hi @chitter99 ,

Saw your work on the Hangouts integration and we'd love to help share it with the Mattermost community. Would you be open to sharing more about your project? https://www.mattermost.org/share-your-mattermost-projects/

Also, we'd like to welcome everyone to join the integrations community on our nightly builds server, if you'd like: https://pre-release.mattermost.com/core/channels/integrations

Wonderful work!

**Comment by chitter99** [comment]
Hi @jasonblais,
I actually already shared my Project on the Integration page. I even got a cup ☕️ for that!

**Comment by jasonblais** [comment]
Ah yes, I see that. Big thanks @chitter99 :)
